### ISSUE TITLE
Newlines in rail feed

### ISSUE THREAD

**Issue by flibbertigibbet** [septadev/GTFS#1]
Attempting to run the [feed validator](https://github.com/google/transitfeed) against the [January 4th release](https://github.com/septadev/GTFS/releases/tag/v20160104) fails with:

```
Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

**Comment by yannick-b** [comment]
issue resolve in  v20160111.1.

**Comment by flibbertigibbet** [comment]
Thanks!
