### ISSUE TITLE
Remove spaces in column definition

### ISSUE THREAD

**Issue by fulldecent** [septadev/GTFS#11]
[Google GTFS file format](https://developers.google.com/transit/gtfs/reference/file-requirements) specifies

> Remove any extra spaces between fields or field names. Many parsers consider the spaces to be part of the value, which may cause errors.

SEPTA rail feed violates this specification, for example, in `calendar.txt`:

    service_id, monday, tuesday, wednesday, thursday, friday, saturday, sunday, start_date, end_date

Instead the correct format should be:

    service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date

Please note that the default CVS import from SQLite will misinterpret SEPTA's data as currently published. This is what happens:

    sqlite> SELECT * FROM calendar;
    service_id," monday"," tuesday"," wednesday"," thursday"," friday"," saturday"," sunday"," start_date"," end_date"

Currently, this is the import script I am using:

https://github.com/fulldecent/septa-regionalrail-otp/blob/master/website/databases/sqliteGTFSImport.txt

**Comment by fulldecent** [comment]
I confirm this is still broken in the new release https://github.com/septadev/GTFS/tree/v20170423.1

**Comment by fulldecent** [comment]
Ping @septadev / confirming this is still broken in the latest version.

Please respond if you recognize this as a valid issue and if a fix is desirable to the project.

**Comment by Wendowski** [comment]
This is fixed in the recent releases of GTFS.

**Comment by fulldecent** [comment]
Much appreciated, thank you
