### ISSUE TITLE
The .zip download is not a valid GTFS file.

### ISSUE THREAD

**Issue by RideSchedules** [septadev/GTFS#14]
Please create separate GTFS files for bus and rail with disambiguated agency_name and agency_id so URLs can be feed directly into software.

**Comment by Wendowski** [comment]
We have two separate GTFS files within the gtfs_public.zip file in the current release. We also have direct links to each gtfs file as follows:

https://www3.septa.org/developer/google_bus.zip
https://www3.septa.org/developer/google_rail.zip
