### ISSUE TITLE
stop_times has duplicate data

### ISSUE THREAD

**Issue by fulldecent** [septadev/GTFS#15]
Unique key constraint is violated in stop_times.

```sh
cat tmp/stop_times.txt | cut -d, -f 1,4 | sort | uniq -d
```

> LAN_541_V55_M,90535

---

If you will consider to add the data latest data directly into the repository (rather than using the GitHub Releases feature) then I could help you to validate this stuff before you publish.  You know my phone number.

**Comment by Wendowski** [comment]
This should be addressed in the recent GTFS releases.
