### ISSUE TITLE
URL to latest data changes

### ISSUE THREAD

**Issue by RideSchedules** [septadev/GTFS#18]
Transit and mapping applications can poll for updates when the URL to the latest file stays the same. 

Updates can be processed and published timely.

**Comment by RideSchedules** [comment]
Can this be relied upon:?

https://github.com/septadev/GTFS/archive/master.zip

**Comment by Wendowski** [comment]
You should be able to use the GitHub current release url for this repo and retrieve the current schedule. It contains an asset () that includes both the Bus and Rail version of the [SEPTA GTFS].(https://github.com/septadev/GTFS/releases/latest/download/gtfs_public.zip) 

To view the current release and the notes: https://github.com/septadev/GTFS/releases/latest 
To download the current GTFS package: https://github.com/septadev/GTFS/releases/latest/download/gtfs_public.zip
