### ISSUE TITLE
Non-Compliant Data Source

### ISSUE THREAD

**Issue by RideSchedules** [septadev/GTFS#19]
Maybe some day SEPTA will have a static URL to compliant GTFS data.

But not today.

**Comment by chadselph** [comment]
There is a static url, thanks to github's [latest release](https://docs.github.com/en/github/administering-a-repository/linking-to-releases) feature:

https://github.com/septadev/GTFS/releases/latest/download/gtfs_public.zip

Unfortunately, `gtfs_public.zip` is not a gtfs file, but instead a zip of two separate gtfs files.

@septadev could you please add `google_bus.zip` / `google_rail.zip` as release assets too? And possibly a combined gtfs with both?

**Comment by RideSchedules** [comment]
Thank you.  I updated your data. 

Please remember to link the latest file as required by Github so this feature actually works.

**Comment by Wendowski** [comment]
Here's links to the separate gtfs files, these are the current release:

https://www3.septa.org/developer/google_bus.zip
https://www3.septa.org/developer/google_rail.zip
