### ISSUE TITLE
Still no static URL for Polling Support

### ISSUE THREAD

**Issue by RideSchedules** [septadev/GTFS#22]
Maybe a good item for the top of the todo list.

**Comment by RideSchedules** [comment]
The words "Latest Release" appears, which is progress.  Now all we need is the link to stay the same and point to the download URL.

**Comment by septadev** [comment]
hi, 

Looking at Github help page: []https://help.github.com/en/github/administering-a-repository/linking-to-releases

SEPTA permanent URL for the latest GTFS feeds is: 
[]https://github.com/septadev/GTFS/releases/latest/download/gtfs_public.zip

(we never change the file name gtfs_public.zip)
