### ISSUE TITLE
Missing frequencies.txt file

### ISSUE THREAD

**Issue by icalouse** [septadev/GTFS#24]
Hello,

In your latest release, stop_times for most bus trips were removed. If these routes are now operating on a headway schedule, there should be a frequencies.txt file to accompany those trips. Without the stop_times, we are simply removing all but a handful of routes from our app. For the time being we are using an older GTFS release.

I should also add that using frequencies.txt instead of individual trips complicates realtime tripUpdates/vehicleLocation matching; we will not be able to display realtime information in our app if there are no distinct trip_ids.

Best,

Nicolas Levy
Transit Data Analyst
[Transit](https://transit.app/)
data@transit.app

**Comment by Wendowski** [comment]
This should be fixed in the current release.

- Kevin
SEPTA IT
