### ISSUE TITLE
 v202005102 release missing gtfs_public.zip

### ISSUE THREAD

**Issue by smsm1** [septadev/GTFS#25]
The latest release version  v202005102 is missing the gtfs_public.zip, thus the Github API is also missing the usual `browser_download_url` data item. This is stopping our download script from updating to the latest data.

Shaun McDonald
Data Operations System Administrator
Ito World

**Comment by yannick-b** [comment]
Shaun, the issue should be resolved.

Thx

Yannick

**Comment by smsm1** [comment]
Yannick,

Thank you, that's fixed the issue.

Shaun
