### ISSUE TITLE
GTFS Missing Data

### ISSUE THREAD

**Issue by ghost** [septadev/GTFS#33]
Hi,

We posted on the Google Group but there is generally little activity there.

This is an issue with the GTFS-RT feed. We've noticed that around the time the Trolley Tunnel Blitz started, the GTFS-RT feed has only been transmitting trolley data occasionally or not at all.

Evidence of this can be seen on the **realtime.septa.org** site where the trolleys for some lines don't show at all, and for a route like the 10, there are two trolleys that have been stuck there for multiple days (it says "updated 600 seconds ago").

Is there any ETA on when this will be fixed?

**Comment by Wendowski** [comment]
This should be resolved. There was an issue with some of the trip ids lining up. The only "600 seconds ago" should be regulated to the trips that haven't been assigned a vehicle in the dispatching software yet, but should be active. Thanks. 

![image](https://github.com/septadev/GTFS/assets/12235301/b89ffc08-2de2-4af1-9314-3e11cd465e4b)
