### ISSUE TITLE
County Line is missing from NHSL

### ISSUE THREAD

**Issue by johndolljr** [septadev/GTFS#5]
stop_times has no corresponding entries for either stop entry

1931,County Line Station - NHSL,40.050063,-75.347341,,,2,0
32191,County Line Station - NHSL,40.050117,-75.347424,,,2,0

**Comment by septadev** [comment]
That, unfortunately, seems to happen more often than not.  County Line Station and Stadium Station sometimes go missing.  I double checked the latest GTFS to be released on Oct 3rd, and both those stations have entries in stop_times.  Will they be in the February 26th GTFS?  I'll tell you on February 24th...
