### ISSUE TITLE
calendar_dates exception_type incorrect for tomorrow, 5th September

### ISSUE THREAD

**Issue by splendidbits** [septadev/GTFS#6]
I believe tomorrow (monday) should be a Sunday service. Exception type 1 indicates that the service is of that type, and 2 indicates it is NOT of that type for that exception. I think you have them reversed?

Also, can you please explain M7. I figure that they are the older sunday schedules as there is no day marked as "1", but confirmation would be very much appreciated.

**Comment by septadev** [comment]
I apologize for the delay in this response -- honestly, I just noticed there were issues associated with this --  and in the future you might get a faster response if you post to our Google Group: https://groups.google.com/forum/#!forum/septadev.  For the question regarding M7, I extracted the previous Sunday schedule added it to the GTFS.  M3 was the normal Sunday which is what they was run on 9/5.

**Comment by splendidbits** [comment]
Thanks a lot for your hard work. Must be a pain to compile.
