### ISSUE TITLE
bus_times GTFS bundle does contains bad calendar entry.

### ISSUE THREAD

**Issue by splendidbits** [septadev/GTFS#7]
calendar-id 4 looks like this 

monday, tuesday, wednesday, thursday, friday, saturday, sunday
0, 0, 0, 0, 0, 0, 0

**Comment by septadev** [comment]
I've been looking through the GTFS Reference and this isn't necessarily a bad calendar entry.  It's a useless calendar entry, sure, but a perfectly valid useless one.  It's more of a reflection of how the schedule is built internally than anything else.  Consider it more of a courtesy, i.e. we plan on using this service_id but sporadically through out its effective date, please see calendar_date.txt for details.
